### ISSUE TITLE
get username not encrypt

### ISSUE THREAD

**Issue by ptitloup** [ccnmtl/django-lti-provider#111]
Hi Susan,
I linked my django project with Moodle and I want to get the username of the user but not encrypt, is-it possible ?
Regards
Nicolas

**Comment by ptitloup** [comment]
After reading the source code, I found the solution. I will purpose a new PR to do that.

**Comment by ptitloup** [comment]
#112

**Comment by sdreher** [comment]
https://pypi.python.org/pypi/django-lti-provider 0.3.3 integrates your PR. Thank you!
