### ISSUE TITLE
Retrieve all LTI post parameters

### ISSUE THREAD

**Issue by ssilverm** [ccnmtl/django-lti-provider#130]
I've noticed that not all the post parameters (custom_canvas_*) are coming through in the LTI object for later views to access.

On line 74 in lti_provider/views.py I added a loop for go through the POST items and add it to the SESSION.  This gives me access to all the LTI parameters later on.

```    
def post(self, request, assignment_name=None):
        for key, value in request.POST.items():
            request.session[key] = value
        ...
        if request.POST.get('ext_content_intended_use', '') == 'embed':
```

Am I going about this the wrong way and I am just not accessing the custom lti parameters the correct way?

**Comment by ssilverm** [comment]
Anything?

**Comment by sdreher** [comment]
Hi - Apologies for the delay in looking at this. You can specify a list of extra properties in your `local_settings.py` via the `LTI_PROPERTY_LIST_EX` setting. This pull request https://github.com/ccnmtl/django-lti-provider/pull/112 updated the code and this issue. We have neglected to update the README about this change. I'll do that now.
