### ISSUE TITLE
Authentication when contained in iframe

### ISSUE THREAD

**Issue by danielmcquillen** [ccnmtl/django-lti-provider#201]
Thanks for making this excellent library available!

I'm working on a test LTI producer (Django 2.2, Python3) that leverages this library for LTI connectivity to an Open edX-based consumer course I'm composing on https://studio.edge.edx.org/.

If I access the producer via the "new window" option in Studio, it works fine and I can see the default landing page and a launch button. However, if I use the "inline" option, which uses an iframe to load the producer, I get the standard django-lti-provider "Authentication Failed" page.

I've set X_FRAME_OPTIONS to 'ALLOW-FROM https://studio.edge.edx.org/', but that didn't seem to help. Any suggestions on other Django configurations that may be blocking iframe access but allowing direct access?

**Comment by danielmcquillen** [comment]
To answer my own question, you need to set the SESSION_COOKIE_SAMESITE config variable to "None" so that Django will recognize the sessionid cookie coming from the iframe.

**Comment by sdreher** [comment]
@danielmcquillen - Great - thanks for the intel and we're glad it is working for you. We haven't completed an EdX integration yet, so it is good to hear this works with them. We've primarily hooked up to LMS like Canvas & Blackboard. Please feel free to create PRs to update doc or other areas as needed.

**Comment by duraiganesh0** [comment]
hello @danielmcquillen I'm facing the same issue now. Can you explain me how you fixed the issue because I followed your instructions and couldn't fix the issue.

**Comment by danielmcquillen** [comment]
Hi Ganesh. We ended up moving away from Open edX as it was too complex for what we wanted to do. Sorry I can't help...if you haven't tried already you should check the Slack forum to see if someone there has advice.

**Comment by duraiganesh0** [comment]
@danielmcquillen can you atleast tell me how you fixed that inline authentication issue? that would be a great hep for me.
