### ISSUE TITLE
Custom User

### ISSUE THREAD

**Issue by dopename** [ccnmtl/django-lti-provider#251]
It looks like there isn't any support for custom user models (i.e. imports into auth.py go directly to django.contrib.auth.models.User). Is there anyway it could support using custom user models through get_user_model() (django.contrib.auth.get_user_model).

I don't know if there are any negative implications of doing so, but thought I'd bring it up!

Please let me know your thoughts, thank you.

**Comment by sdreher** [comment]
Sure, that would be a good enhancement. We would welcome a pull request if you wanted to put one together.
